version: '3.8'

services:
  # React Frontend Application
  daily-journal-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily-journal-app
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://localhost:5000}
      - REACT_APP_MAX_VIDEO_SIZE=${REACT_APP_MAX_VIDEO_SIZE:-104857600}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s